@startuml AD02_KupovinaClanarine
title Dijagram aktivnosti - Kupovina članarine

|Član teretane|
start
:Pokretanje opcije za\nkupovinu članarine;

|Sistem|
if (Član već ima aktivnu članarinu?) then (Da)
  :Prikaz informacije o\npostojećoj članarini;
  :Ponuda opcije produženja;
  |Član teretane|
  if (Bira produženje?) then (Da)
    :Odabir produženja članarine;
  else (Ne)
    :Odustajanje od kupovine;
    end
  endif
else (Ne)
  :Prikaz dostupnih tipova\nčlanarina sa cijenama;
endif

|Član teretane|
:Odabir tipa članarine\n(mjesečna, kvartalna, godišnja);

|Sistem|
:Prikaz detalja odabrane\nčlanarine i ukupne cijene;

|Član teretane|
:Potvrda kupovine;

|Sistem|
:Evidentiranje plaćanja;
:Aktiviranje članarine;
:Izračun datuma isteka;
:Prikaz potvrde kupovine\nsa datumom isteka;

stop

@enduml
